[package]
name = "summa-wallet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libwallet = { git = "https://github.com/virto-network/libwallet" }
matrix-sdk = "0.4.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
tokio = { version = "1", features = ["full"] }
# async-std = { version = "1.10.0", features = ["attributes"] }
serde = "1.0.130"