[package]
name = "summa-wallet"
version = "0.1.0"
edition = "2018"

[dependencies]
libwallet = { version = "0.1.0", git = "https://github.com/virto-network/libwallet", default-features = false }

[features]
std = [
	"libwallet/std"
]
